### ISSUE TITLE
端口添加逻辑问题

### ISSUE THREAD

**Issue by wooyin** [L-codes/MX1014#1]
问题代码：defaultPorts = append(commonPorts, defaultPorts...)。第455行，默认添加commonPorts共计49个端口
问题描述：执行 go run mx1014.go -p 80 127.0.0.1 或者 go run mx1014.go 127.0.0.1:80 时，默认会扫49个端口，而不是单独80端口。
修复建议：加个判断，在有-ap参数 或者 没有-p参数 或者 IP后面没有跟端口的情况下，再使用commonPorts端口

**Comment by L-codes** [comment]
感谢问题提交，`go run mx1014.go -p 80 127.0.0.1` 确实存在逻辑问题，`go run mx1014.go 127.0.0.1:80` 是不会扫49个端口的，是当时的测试代码没有删除导致的逻辑问题，新版 v1.1.1 中已解决

**Comment by wooyin** [comment]
go run mx1014.go 127.0.0.1:80好像是会扫描
<img width="760" alt="图片" src="https://user-images.githubusercontent.com/48854942/117454286-8eb38c80-af78-11eb-860f-cff16bf71947.png">
