### ISSUE TITLE
建议加个slient模式输出

### ISSUE THREAD

**Issue by wooyin** [L-codes/MX1014#2]
-o参数会打印所有输出，但更多时候只关心存活的IP端口信息

**Comment by L-codes** [comment]
slient 模式应该为，程序不输出，但是-o 会保存数据，这个后续会考虑添加；
你的需求是仅打印开放端口信息对吧，但是我已将所有非端口开放信息用 `# xxx`的格式打印，即你可以`grep -v '^#'`的形式过滤掉非端口开放信息(注意 程序的标准输出是stderr)

**Comment by wooyin** [comment]
阔以
